<?php

namespace HomePage\HomePageBundle\Repository;

/**
 * articlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articlesRepository extends \Doctrine\ORM\EntityRepository
{
}
